/// Flutter icons SignUpIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SignUpIcon
///      fonts:
///       - asset: fonts/SignUpIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SignUpIcon {
  SignUpIcon._();

  static const _kFontFam = 'SignUpIcon';
  static const String? _kFontPkg = null;

  static const IconData male_add = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
